[supervisord]
nodaemon=true

logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[inet_http_server]
port=0.0.0.0:9001

[supervisorctl]
serverurl=http://127.0.0.1:9001

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/apache2-stdout.log
stderr_logfile=/var/log/supervisor/apache2-stderr.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/cron-stdout.log
stderr_logfile=/var/log/supervisor/cron-stderr.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:messenger]
command=php /var/www/html/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
autostart=true
autorestart=true
numprocs=2
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/messenger-stdout.log
stderr_logfile=/var/log/supervisor/messenger-stderr.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:scheduler]
command=php /var/www/html/bin/console scheduler:consume --time-limit=3600
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/supervisor/scheduler-stdout.log
stderr_logfile=/var/log/supervisor/scheduler-stderr.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
