#!/bin/bash

# Script CLI para executar comandos Symfony console no container
# Uso: cli/sf <comando>
# Exemplo: cli/sf cache:clear
# Exemplo: cli/sf make:entity
# Exemplo: cli/sf doctrine:migrations:migrate

COMPOSE_CMD=${COMPOSE_DEV_CMD:-"docker compose --env-file devops/ports.env -f devops/docker-compose.yaml"}

if [ $# -eq 0 ]; then
    # Se não passar argumentos, lista os comandos disponíveis
    $COMPOSE_CMD exec symfony php bin/console list
else
    # Executa o comando Symfony console
    $COMPOSE_CMD exec symfony php bin/console "$@"
fi
