# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(MEDIA_STORAGE_PATH): './var/storage'
    env(GOOGLE_CLIENT_ID): ''
    env(GOOGLE_CLIENT_SECRET): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\Seguranca\CriptografiaService:
        arguments:
            $chaveSecreta: '%env(APP_SECRET)%'

    App\Service\DistribuirLocalService:
        arguments:
            $mediaStoragePath: '%env(MEDIA_STORAGE_PATH)%'
            $projectDir: '%kernel.project_dir%'

    App\Service\GoogleFotosOAuthService:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'

    GuzzleHttp\ClientInterface: '@guzzle.default'

    guzzle.default:
        class: GuzzleHttp\Client

    guzzle.google_photos:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: 'https://photoslibrary.googleapis.com' }

    guzzle.google_oauth:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: 'https://oauth2.googleapis.com' }

    App\Infra\GoogleFotos\GoogleFotosAPI:
        arguments:
            $client: '@guzzle.google_photos'
            $baseUrl: 'https://photoslibrary.googleapis.com'

    App\Infra\GoogleOAuth\GoogleOAuthAPI:
        arguments:
            $client: '@guzzle.google_oauth'
            $baseUrl: 'https://oauth2.googleapis.com'

